import js from '@eslint/js';
import globals from 'globals';
import reactHooks from 'eslint-plugin-react-hooks';
import tseslint from 'typescript-eslint';
import prettier from 'eslint-config-prettier';

/*
 * One config for both packages.
 *
 * The server and client are independent npm packages, but they share a
 * language, a style, and a reviewer. Keeping the rules in one file means they
 * cannot drift apart, and the per-directory blocks below carry the parts that
 * genuinely differ — Node globals versus browser globals, and React's hook
 * rules, which have nothing to apply to on the server.
 *
 * Deliberately the non-type-checked ruleset. The type-aware rules are stricter
 * and worth adopting, but they report several hundred findings against
 * Mongoose documents and parsed JSON on a codebase that has never been linted.
 * A linter that fails loudly on its first run gets switched off. Start here,
 * tighten later.
 */
export default tseslint.config(
  {
    ignores: [
      '**/node_modules/**',
      '**/dist/**',
      'client/public/**',
      // Generated by npm, not written by hand.
      '**/package-lock.json',
    ],
  },

  js.configs.recommended,
  tseslint.configs.recommended,

  {
    rules: {
      // The codebase uses a leading underscore for deliberately unused
      // bindings — Express's `_req`, `_next` — which is a convention worth
      // keeping rather than an oversight worth reporting.
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrors: 'none',
        },
      ],
      // `catch {}` with a comment explaining why is used deliberately in
      // several places; an empty block with no comment is still an error.
      'no-empty': ['error', { allowEmptyCatch: true }],
      // Augmenting Express's Request with `userId` requires declaration
      // merging into the Express namespace — there is no module-syntax
      // alternative, so the rule's advice does not apply to an ambient
      // declaration. Namespaces in real code are still an error.
      '@typescript-eslint/no-namespace': ['error', { allowDeclarations: true }],
    },
  },

  {
    // The smoke suite reads arbitrary JSON off the wire and indexes into it
    // (`body.room.members[0].role`). `unknown` would be more honest and would
    // also mean a cast at several hundred call sites in one 1,300-line file,
    // for a script whose assertions are the actual type check.
    files: ['server/scripts/**/*.ts'],
    rules: {
      '@typescript-eslint/no-explicit-any': 'off',
    },
  },

  {
    files: ['server/**/*.ts'],
    languageOptions: {
      globals: globals.node,
    },
  },

  {
    files: ['client/**/*.{ts,tsx}'],
    languageOptions: {
      globals: { ...globals.browser, ...globals.worker },
    },
    ...reactHooks.configs.flat.recommended,
  },

  {
    files: ['*.js', 'client/vite.config.ts', 'client/vitest.config.ts'],
    languageOptions: {
      globals: globals.node,
    },
  },

  // Last, so it can switch off every stylistic rule that would fight Prettier.
  prettier,
);
